export interface JobLibraryTemplate {
  id: string;
  name: string;
  description: string;
  tags: string[];
  schedule: string;
  prompt: string;
  timeout?: number;
}

export const JOB_LIBRARY_TEMPLATES: JobLibraryTemplate[] = [
  {
    id: "weekly-strategy-digest",
    name: "Weekly strategy digest",
    description: "Summarize the week, call out shifts, and leave a concise strategy note in the KB.",
    tags: ["strategy", "leadership", "planning"],
    schedule: "0 9 * * 1",
    timeout: 900,
    prompt: [
      "Review the most important changes across the knowledge base and current workspace files from the past week.",
      "Write a short strategy digest with key signals, risks, wins, and three next recommendations.",
      "Save the result to a KB page for weekly strategy updates and reference any supporting pages you used.",
    ].join("\n"),
  },
  {
    id: "daily-priority-check",
    name: "Daily priority check",
    description: "Scan current work and leave a short morning priorities note for the team.",
    tags: ["planning", "operations", "leadership"],
    schedule: "0 9 * * 1-5",
    timeout: 600,
    prompt: [
      "Review the latest roadmap, active planning pages, and recent agent output.",
      "Write a short daily priority note with what matters today, blockers, and what can wait.",
      "Save the note to the KB in the team's daily planning area.",
    ].join("\n"),
  },
  {
    id: "competitor-watch",
    name: "Competitor watch",
    description: "Update a running competitor-watch note with product, pricing, or messaging changes.",
    tags: ["research", "marketing", "product"],
    schedule: "0 14 * * 1-5",
    timeout: 900,
    prompt: [
      "Review the competitor research pages and update the running competitor watch note.",
      "Highlight changes in positioning, launches, pricing, or messaging that matter for Cabinet.",
      "Keep the KB page crisp and append only the most relevant new insights.",
    ].join("\n"),
  },
  {
    id: "kpi-snapshot",
    name: "KPI snapshot",
    description: "Produce a quick metrics snapshot and note unusual movement.",
    tags: ["analytics", "metrics", "reporting"],
    schedule: "0 10 * * 1-5",
    timeout: 600,
    prompt: [
      "Review the latest KPI, analytics, and reporting pages in the KB.",
      "Create a short KPI snapshot with the top numbers, trend direction, and any anomalies worth attention.",
      "Save the updated snapshot into the KB and reference the source pages.",
    ].join("\n"),
  },
  {
    id: "doc-gardener",
    name: "Doc gardener",
    description: "Clean stale pages, fix broken structure, and leave docs more navigable than before.",
    tags: ["documentation", "operations", "knowledge-base"],
    schedule: "0 16 * * 2,4",
    timeout: 900,
    prompt: [
      "Inspect the documentation and planning pages for stale sections, broken links, or obvious duplication.",
      "Make a small batch of concrete cleanups directly in the KB.",
      "Leave a short summary of what was cleaned and which pages still need follow-up.",
    ].join("\n"),
  },
  {
    id: "customer-signal-roundup",
    name: "Customer signal roundup",
    description: "Gather customer-facing signals into one concise roundup for the team.",
    tags: ["customer-success", "support", "product"],
    schedule: "0 11 * * 1,3,5",
    timeout: 900,
    prompt: [
      "Review customer feedback, campaign notes, support signals, and product observations in the KB.",
      "Create a concise roundup of what customers are saying, repeating, or struggling with.",
      "Save the roundup to the KB and surface any urgent signal that should influence priorities.",
    ].join("\n"),
  },
  {
    id: "content-calendar-refresh",
    name: "Content calendar refresh",
    description: "Update the editorial calendar with fresh themes, gaps, and publishing priorities.",
    tags: ["marketing", "content", "editorial"],
    schedule: "0 9 * * 1",
    timeout: 900,
    prompt: [
      "Review the content roadmap, campaign pages, and recently published materials.",
      "Refresh the editorial calendar with the highest-priority upcoming themes, formats, and owners.",
      "Note which topics need research, which can be repurposed, and what should be deprioritized.",
    ].join("\n"),
  },
  {
    id: "seo-opportunity-scan",
    name: "SEO opportunity scan",
    description: "Find search opportunities, content gaps, and on-page improvement ideas.",
    tags: ["seo", "marketing", "content"],
    schedule: "0 10 * * 2,4",
    timeout: 900,
    prompt: [
      "Review SEO notes, keyword research, landing pages, and recent content performance summaries.",
      "Identify the strongest SEO opportunities, including content gaps, internal-linking wins, and on-page fixes.",
      "Leave a prioritized shortlist with why each opportunity matters and what page it should affect.",
    ].join("\n"),
  },
  {
    id: "backlink-outreach-ideas",
    name: "Backlink outreach ideas",
    description: "Prepare a concise list of backlink and partnership outreach opportunities.",
    tags: ["seo", "partnerships", "marketing"],
    schedule: "0 13 * * 2",
    timeout: 900,
    prompt: [
      "Review partnership notes, competitor mentions, PR opportunities, and SEO research in the KB.",
      "Create a concise list of backlink or co-marketing outreach opportunities with context and rationale.",
      "Prioritize the highest-leverage opportunities and note what angle would likely resonate.",
    ].join("\n"),
  },
  {
    id: "campaign-performance-brief",
    name: "Campaign performance brief",
    description: "Summarize campaign performance, signal what is working, and suggest the next move.",
    tags: ["marketing", "analytics", "performance"],
    schedule: "0 15 * * 1-5",
    timeout: 900,
    prompt: [
      "Review recent campaign reports, experiment notes, and channel performance pages.",
      "Create a short campaign performance brief covering wins, weak spots, and notable movement.",
      "Suggest the next concrete optimization steps by channel or campaign theme.",
    ].join("\n"),
  },
  {
    id: "newsletter-draft-prep",
    name: "Newsletter draft prep",
    description: "Prepare a draft structure and talking points for the next newsletter.",
    tags: ["marketing", "content", "newsletter"],
    schedule: "0 11 * * 3",
    timeout: 900,
    prompt: [
      "Review recent announcements, launches, content pieces, and customer-facing updates.",
      "Prepare a suggested newsletter outline with headline options, key sections, and supporting links.",
      "Keep the draft concise and easy for a marketer or editor to turn into a final send.",
    ].join("\n"),
  },
  {
    id: "social-content-batch",
    name: "Social content batch",
    description: "Generate a small batch of ready-to-review social post ideas from current work.",
    tags: ["marketing", "social", "content"],
    schedule: "0 10 * * 1,3,5",
    timeout: 900,
    prompt: [
      "Review current launches, roadmap updates, customer stories, and new content in the KB.",
      "Generate a short batch of social post ideas with a hook, angle, and suggested CTA for each.",
      "Group the ideas by theme and prioritize the ones that feel most timely or high-signal.",
    ].join("\n"),
  },
  {
    id: "sales-pipeline-snapshot",
    name: "Sales pipeline snapshot",
    description: "Summarize pipeline health, notable movement, and top follow-up priorities.",
    tags: ["sales", "crm", "reporting"],
    schedule: "0 9 * * 1-5",
    timeout: 600,
    prompt: [
      "Review sales notes, deal trackers, CRM summaries, and customer conversations in the KB.",
      "Create a concise pipeline snapshot with key movements, stalled deals, and top follow-up priorities.",
      "Highlight any risks, likely wins, and actions the sales team should take next.",
    ].join("\n"),
  },
  {
    id: "stalled-deals-review",
    name: "Stalled deals review",
    description: "Inspect stalled opportunities and propose specific reactivation angles.",
    tags: ["sales", "customer-success", "crm"],
    schedule: "0 14 * * 2,4",
    timeout: 900,
    prompt: [
      "Review stalled or inactive deal notes, objections, and prior outreach history.",
      "Identify why each promising opportunity may have stalled and propose a specific reactivation angle.",
      "Leave concise next-step suggestions for the sales owner, including what message or offer to test.",
    ].join("\n"),
  },
  {
    id: "objection-pattern-report",
    name: "Objection pattern report",
    description: "Extract the main sales objections showing up and suggest responses.",
    tags: ["sales", "enablement", "research"],
    schedule: "0 12 * * 3",
    timeout: 900,
    prompt: [
      "Review sales call notes, lost-deal summaries, support feedback, and buyer questions.",
      "Identify the main objection patterns and cluster them into a short report.",
      "For each pattern, suggest a clearer response, asset, or proof point that could improve conversion.",
    ].join("\n"),
  },
  {
    id: "lead-follow-up-queue",
    name: "Lead follow-up queue",
    description: "Build a short prioritized queue of leads or accounts that deserve follow-up.",
    tags: ["sales", "crm", "prioritization"],
    schedule: "0 8 * * 1-5",
    timeout: 600,
    prompt: [
      "Review recent lead activity, account notes, inbound requests, and open follow-up items.",
      "Create a short prioritized follow-up queue with the reason each lead or account is worth attention now.",
      "Include suggested message angles or next actions where possible.",
    ].join("\n"),
  },
  {
    id: "bug-triage-digest",
    name: "Bug triage digest",
    description: "Summarize recent bugs, cluster patterns, and suggest triage priorities.",
    tags: ["development", "engineering", "qa"],
    schedule: "0 10 * * 1-5",
    timeout: 900,
    prompt: [
      "Review bug reports, issue trackers, QA notes, and recent regressions documented in the KB.",
      "Create a bug triage digest that clusters related issues and suggests a practical priority order.",
      "Call out anything that looks systemic, user-facing, or likely to create repeated support load.",
    ].join("\n"),
  },
  {
    id: "technical-debt-sweep",
    name: "Technical debt sweep",
    description: "Identify the most worthwhile technical debt items to address next.",
    tags: ["development", "engineering", "maintenance"],
    schedule: "0 15 * * 2",
    timeout: 900,
    prompt: [
      "Review engineering notes, architecture docs, bug patterns, and TODO-heavy areas in the KB.",
      "Identify the highest-leverage technical debt items and explain the tradeoff for addressing each one.",
      "Recommend a short sequence of debt cleanup work that improves reliability or team speed.",
    ].join("\n"),
  },
  {
    id: "release-readiness-check",
    name: "Release readiness check",
    description: "Audit current release notes and open items before a release window.",
    tags: ["development", "release", "qa"],
    schedule: "0 11 * * 4",
    timeout: 900,
    prompt: [
      "Review release notes, QA checklists, open bugs, and launch dependencies documented in the KB.",
      "Produce a concise release-readiness check with blockers, watch-outs, and final confirmation steps.",
      "Make it easy for the team to decide whether the current release window is safe to proceed.",
    ].join("\n"),
  },
  {
    id: "incident-review-prep",
    name: "Incident review prep",
    description: "Prepare a concise incident review draft from recent production issues.",
    tags: ["development", "devops", "reliability"],
    schedule: "0 13 * * 1",
    timeout: 900,
    prompt: [
      "Review recent incidents, outage notes, alerts, and post-release problems in the KB.",
      "Prepare a concise incident review draft covering what happened, impact, likely root cause, and follow-ups.",
      "Keep it factual and useful for turning into a lightweight retrospective.",
    ].join("\n"),
  },
  {
    id: "product-feedback-cluster",
    name: "Product feedback cluster",
    description: "Cluster product feedback into recurring needs, friction, and opportunity areas.",
    tags: ["product", "research", "analytics"],
    schedule: "0 11 * * 2,5",
    timeout: 900,
    prompt: [
      "Review user interviews, support feedback, sales notes, and product observations in the KB.",
      "Cluster the strongest recurring feedback themes into a concise product insights note.",
      "Separate urgent friction from longer-term opportunities and note what seems to be growing in frequency.",
    ].join("\n"),
  },
  {
    id: "roadmap-risks-check",
    name: "Roadmap risks check",
    description: "Scan roadmap work for sequencing risks, dependencies, and unclear decisions.",
    tags: ["product", "planning", "leadership"],
    schedule: "0 10 * * 1,4",
    timeout: 900,
    prompt: [
      "Review active roadmap plans, milestone notes, dependencies, and open decisions in the KB.",
      "Identify the biggest roadmap risks, especially sequencing problems, hidden dependencies, or vague ownership.",
      "Suggest what should be clarified or re-ordered before the risks become blockers.",
    ].join("\n"),
  },
  {
    id: "experiment-backlog-refresh",
    name: "Experiment backlog refresh",
    description: "Refresh the experiment backlog with sharper hypotheses and next bets.",
    tags: ["product", "growth", "experiments"],
    schedule: "0 14 * * 3",
    timeout: 900,
    prompt: [
      "Review experiment notes, performance trends, customer behavior observations, and roadmap goals.",
      "Refresh the experiment backlog with sharper hypotheses, a likely success signal, and a suggested priority.",
      "Keep the output concise and focused on high-potential, realistic next bets.",
    ].join("\n"),
  },
  {
    id: "research-insight-digest",
    name: "Research insight digest",
    description: "Turn scattered research notes into a concise insight digest for the team.",
    tags: ["research", "product", "strategy"],
    schedule: "0 16 * * 2",
    timeout: 900,
    prompt: [
      "Review interview notes, discovery docs, competitor analysis, and observation pages in the KB.",
      "Synthesize the clearest research insights into a short digest with implications for product or messaging.",
      "Highlight what feels newly validated, still uncertain, or surprisingly consistent across sources.",
    ].join("\n"),
  },
  {
    id: "support-ticket-themes",
    name: "Support ticket themes",
    description: "Summarize the strongest support patterns and which issues need escalation.",
    tags: ["support", "customer-success", "operations"],
    schedule: "0 9 * * 1-5",
    timeout: 600,
    prompt: [
      "Review recent support ticket summaries, bug reports, and customer complaints documented in the KB.",
      "Identify the strongest repeating support themes and what each one implies.",
      "Escalate anything that looks urgent, user-facing, or expensive in repeat effort.",
    ].join("\n"),
  },
  {
    id: "onboarding-friction-review",
    name: "Onboarding friction review",
    description: "Look for friction in onboarding flows and propose practical improvements.",
    tags: ["support", "product", "customer-success"],
    schedule: "0 13 * * 3,5",
    timeout: 900,
    prompt: [
      "Review onboarding notes, customer questions, activation feedback, and support pain points in the KB.",
      "Identify the biggest onboarding friction points and suggest practical improvements.",
      "Keep the output focused on the changes most likely to improve activation or reduce repeated confusion.",
    ].join("\n"),
  },
  {
    id: "finance-variance-note",
    name: "Finance variance note",
    description: "Summarize budget or performance variance and where to look closer.",
    tags: ["finance", "analytics", "reporting"],
    schedule: "0 10 * * 1",
    timeout: 900,
    prompt: [
      "Review budget notes, spending summaries, revenue snapshots, and forecast pages in the KB.",
      "Create a concise variance note covering unusual movement, likely explanations, and where to look closer.",
      "Flag anything that seems structurally off rather than just noisy week-to-week change.",
    ].join("\n"),
  },
  {
    id: "ops-risk-check",
    name: "Ops risk check",
    description: "Review operational plans and surface the most important delivery or coordination risks.",
    tags: ["operations", "planning", "leadership"],
    schedule: "0 15 * * 1,3",
    timeout: 900,
    prompt: [
      "Review operating plans, team notes, process docs, and active coordination issues in the KB.",
      "Identify the biggest operational risks or handoff problems that could slow execution.",
      "Suggest the next few actions that would reduce ambiguity, delay, or repeated misalignment.",
    ].join("\n"),
  },
  {
    id: "meeting-brief-builder",
    name: "Meeting brief builder",
    description: "Prepare a concise brief for the next recurring team sync or leadership review.",
    tags: ["operations", "leadership", "planning"],
    schedule: "0 8 * * 1",
    timeout: 600,
    prompt: [
      "Review the latest planning notes, updates, unresolved issues, and recent agent output in the KB.",
      "Prepare a concise meeting brief with the most important updates, discussion points, and decisions needed.",
      "Keep it short, clear, and ready to use in a recurring sync or review meeting.",
    ].join("\n"),
  },
  {
    id: "design-qa-pass",
    name: "Design QA pass",
    description: "Summarize UI or design inconsistencies and suggest cleanup priorities.",
    tags: ["design", "qa", "product"],
    schedule: "0 14 * * 4",
    timeout: 900,
    prompt: [
      "Review design notes, UI polish issues, brand guidance, and QA observations in the KB.",
      "Create a concise design QA pass note with inconsistencies, rough edges, and cleanup priorities.",
      "Prioritize the issues that most affect trust, usability, or overall product quality.",
    ].join("\n"),
  },
  {
    id: "community-signal-digest",
    name: "Community signal digest",
    description: "Collect community or audience signals into a short actionable digest.",
    tags: ["marketing", "community", "research"],
    schedule: "0 12 * * 2,4",
    timeout: 900,
    prompt: [
      "Review community notes, social feedback, audience questions, and public-facing reactions documented in the KB.",
      "Create a short digest of what the audience is noticing, asking for, or reacting to.",
      "Highlight the signals that should influence content, positioning, or product communication.",
    ].join("\n"),
  },
];
